services:
  mariadb:
    image: mariadb:10.7.3
    restart: always
    container_name: mariadb-ci
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    networks:
      - ci_network

networks:
  ci_network:
    external: true
